@echo off
cd /d "%~dp0"
echo Starting Python RAG server (granian)...
start "史鉴-RAG-Server" cmd /c "granian --interface asgi server:app --port 8080 --host 127.0.0.1 --workers 1"
echo Starting Vite dev server...
"D:\Program Files\nodejs\npm.cmd" run dev -- --host 127.0.0.1 --port 5300 --strictPort
